ALTER TYPE "ReluProcessingDomain" ADD VALUE IF NOT EXISTS 'ESCO';
ALTER TYPE "ReluProcessingDomain" ADD VALUE IF NOT EXISTS 'NACE';
ALTER TYPE "ReluProcessingDomain" ADD VALUE IF NOT EXISTS 'UNICLASS';
ALTER TYPE "ReluProcessingDomain" ADD VALUE IF NOT EXISTS 'INTENT';
ALTER TYPE "ReluProcessingDomain" ADD VALUE IF NOT EXISTS 'SUMMARY';
ALTER TYPE "ReluProcessingDomain" ADD VALUE IF NOT EXISTS 'GEOGRAPHY';
