steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/openstaff-platform/openstaff-repo/openstaff-admin:$BUILD_ID'
      - '-t'
      - 'europe-west1-docker.pkg.dev/openstaff-platform/openstaff-repo/openstaff-admin:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://api.openstaff.eu'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
      - '-f'
      - 'apps/admin/Dockerfile'
      - 'apps/admin'
    id: 'build-admin'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-west1-docker.pkg.dev/openstaff-platform/openstaff-repo/openstaff-admin'
    id: 'push-admin'
    waitFor: ['build-admin']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'openstaff-admin'
      - '--image=europe-west1-docker.pkg.dev/openstaff-platform/openstaff-repo/openstaff-admin:$BUILD_ID'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3001'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=5'
      - '--set-env-vars=NODE_ENV=production,NEXT_PUBLIC_API_URL=https://api.openstaff.eu'
    id: 'deploy-admin'
    waitFor: ['push-admin']

images:
  - 'europe-west1-docker.pkg.dev/openstaff-platform/openstaff-repo/openstaff-admin:$BUILD_ID'
  - 'europe-west1-docker.pkg.dev/openstaff-platform/openstaff-repo/openstaff-admin:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_MEDIUM

substitutions:
  _NEXT_PUBLIC_FIREBASE_API_KEY: ''
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ''
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: ''
  _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ''
  _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ''
  _NEXT_PUBLIC_FIREBASE_APP_ID: ''
